var Grid = tui.Grid;

class CustomSliderRenderer {
  constructor(props) {
    const el = document.createElement('input');
    const { min, max } = props.columnInfo.renderer.options;

    el.type = 'range';
    el.min = String(min);
    el.max = String(max);

    el.addEventListener('mousedown', (ev) => {
      ev.stopPropagation();
    });
    console.log(el);
    this.el = el;
    console.log(el);

    this.render(props);
  }

  getElement() {
    return this.el;
  }

  render(props) {
    this.el.value = String(props.value);
  }
}

const grid = new Grid({
  el: document.getElementById('wrapper'),
  scrollX: false,
  scrollY: false,
  //   header: {
  //     height: 160,
  //     complexColumns: [
  //       {
  //         header: 'Basic',
  //         name: 'mergeColumn1',
  //         childNames: ['name', 'artist'],
  //       },
  //       {
  //         header: 'Extra',
  //         name: 'mergeColumn2',
  //         childNames: ['type', 'release', 'genre'],
  //       },
  //       {
  //         header: 'Detail',
  //         name: 'mergeColumn3',
  //         childNames: ['mergeColumn1', 'mergeColumn2'],
  //       },
  //       {
  //         header: 'Count',
  //         name: 'mergeColumn4',
  //         childNames: ['downloadCount', 'listenCount'],
  //       },
  //       {
  //         header: 'Album Info',
  //         name: 'mergeColumn5',
  //         childNames: ['price', 'mergeColumn3', 'mergeColumn4'],
  //       },
  //     ],
  //   },
  columns: [
    {
      header: 'Name',
      name: 'name',
      filter: { type: 'text', showApplyBtn: true, showClearBtn: true },
      sortingType: 'desc',
      sortable: true,
    },
    {
      header: 'Artist',
      name: 'artist',
      filter: 'select',
      sortingType: 'desc',
      sortable: true,
    },
    {
      header: 'Type',
      name: 'type',
      sortingType: 'desc',
      sortable: true,
    },
    {
      header: 'Release',
      name: 'release',
      filter: {
        type: 'date',
        options: {
          format: 'yyyy.MM.dd',
        },
      },
      sortingType: 'desc',
      sortable: true,
    },
    {
      header: 'Genre',
      name: 'genre',
      name: 'genre',
      filter: {
        type: 'text',
        operator: 'OR',
      },
      sortingType: 'desc',
      sortable: true,
    },
    {
      header: 'Price',
      name: 'price',
      filter: 'number',
      sortingType: 'desc',
      sortable: true,
    },
    {
      header: 'Download',
      name: 'downloadCount',
      filter: 'number',
      sortingType: 'desc',
      sortable: true,
    },
    {
      header: 'Listen',
      name: 'listenCount',
      filter: 'number',
      sortingType: 'desc',
      sortable: true,
    },
  ],
  data: [
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
    {
      name: 'Beautiful Lies',
      artist: 'Birdy',
      type: 'Deluxe',
      release: '2016.03.26',
      genre: 'Pop',
      price: 39560,
      downloadCount: 1000,
      listenCount: 5503,
    },
  ],
});
